OrchidOs : settings cleanup
This reverts commit dae447483b0fe3ed94f173deb2b936b828d676bb.
Revert "Update awaken_styles.xml"
This reverts commit 72329d9264260fb2594202024b4652be49f3eaf5.

Update top_level_settings.xml
Update dimens.xml
Update top_level_settings.xml

error

Themes.java:51: error: cannot find symbol
    private SystemSettingListPreference mSettingsDashBoardGms;
            ^
  symbol:   class SystemSettingListPreference
  location: class Themes

Update colors.xml