OrchidOs Settings  : settings cleanup and UI improvements
Update my_device_info.xml
Settings: Use actual default refresh rate
* Do not hardcode to 60.
Settings: Expand all advanced settings by default
A lot of the time, the settings I'm actually looking for are under
"advanced", which slows down my navigation to the target setting by
making me tap "Advanced" to expand it.
These hidden advanced sections are also bad for user discoverability
because it means that the user needs to expand all advanced sections in
order to discover all of the settings. It also makes the user hesitate
and scan through the non-advanced options first to determine whether the
option they're looking for is under advanced, since the advanced vs.
non-advanced grouping is often quite unintuitive. Realistically, with
discoverability and ease of access in mind, I can't think of a situation
in which the advanced sections will actually be helpful.
EmergencySettings: Drop preference more_emergency_settings
security_dashboard_settings: Remove empty Security status header

-- Adapt for Preference being part of support library

spezi77: Adapt for Android 10

Change-Id: Ic721fdc7f63607d972d203e1a13097e8870bce2f
Signed-off-by: spezi77 <spezi7713@gmx.net>
Signed-off-by: NurKeinNeid <mralexman3000@gmail.com>
Co-Authored-By: 33bca <fabian.leutenegger@bluewin.ch>
Co-Authored-By: minaripenguin <alexfinhart@gmail.com>

OrchidOs : settings cleanup and build fixes

OrchidOs : settings cleanup

Themes.java:51: error: cannot find symbol
    private SystemSettingListPreference mSettingsDashBoardGms;
            ^
  symbol:   class SystemSettingListPreference
  location: class Themes
packages/apps/Settings/res/values/dimens.xml:499: error: duplicate value for resource 'dimen/op_control_icon_size_indicator' with config ''.
packages/apps/Settings/res/values/dimens.xml:499: error: resource previously defined here.
packages/apps/Settings/res/values/dimens.xml: error: file failed to compile.
packages/apps/Settings/res/values/strings.xml:32: error: duplicate value for resource 'string/storage_warning_internal' with config ''.
packages/apps/Settings/res/values/strings.xml:32: error: resource previously defined here.
packages/apps/Settings/res/values/strings.xml: error: file failed to compile.